# Generated by Django 2.2 on 2019-11-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='/img')),
                ('tag', models.TextField()),
                ('target', models.TextField()),
                ('aim', models.TextField()),
                ('description', models.TextField()),
                ('prohibition', models.TextField()),
                ('price_day', models.IntegerField()),
                ('price_week', models.IntegerField()),
                ('breakfast_info', models.TextField()),
                ('breakfast_image', models.FilePathField(path='/img')),
                ('brunch_info', models.TextField()),
                ('brunch_image', models.FilePathField(path='/img')),
                ('lunch_info', models.TextField()),
                ('lunch_image', models.FilePathField(path='/img')),
                ('dunch_info', models.TextField()),
                ('dunch_image', models.FilePathField(path='/img')),
                ('dinner_info', models.TextField()),
                ('dinner_image', models.FilePathField(path='/img')),
            ],
        ),
    ]
