# Generated by Django 2.1.1 on 2019-11-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20191125_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.TextField(),
        ),
    ]
